# Generated by Django 5.2.8 on 2025-11-10 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 10, 14, 55, 59, 993135)
            ),
        ),
    ]
