# Generated by Django 5.2.8 on 2025-11-12 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_customuser_date_joined_chanel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chanel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 15, 36, 1, 399827)
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 15, 36, 1, 397026)
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_link", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chanel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="mainapp.chanel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chanel",
            name="publications",
            field=models.ManyToManyField(
                blank=True, related_name="chanel_posts", to="mainapp.post"
            ),
        ),
    ]
