# Generated by Django 5.2.8 on 2025-11-12 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0004_alter_chanel_created_at_alter_customuser_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chanel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 16, 7, 4, 919262)
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 16, 7, 4, 917314)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
