# Generated by Django 5.2.8 on 2025-11-12 18:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0005_alter_chanel_created_at_alter_customuser_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chanel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 18, 18, 38, 863469)
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 12, 18, 18, 38, 861452)
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mainapp.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="comments_list",
            field=models.ManyToManyField(
                blank=True, related_name="post_comments", to="mainapp.comment"
            ),
        ),
    ]
